angular.module(
  'client',
  [
    'ngSanitize',
    'ui.router',
    'ngResource',
    'ngAnimate',
    'ngEnter',
    'ngCookies',
    'anim-in-out',
    'angular-growl',
    'NgActive',
    'ngFileUpload',
    'fileModel',
    'imageFillfield',
    'angular-carousel',
    'ngTouch',
    'ui.select',
    'firebase',
    'infinite-scroll'
    'angular.filter'
    'ngImgCrop'
    'rzModule'
    'ngTagsInput'
    'angular-google-analytics'
    'angular-svg-round-progressbar'
  ]
)
