angular.module(
  'client',
  [
    'ngSanitize',
    'ui.router',
    'ngResource',
    'ngAnimate',
    'ngEnter',
    'anim-in-out',
    'angular-growl',
    'NgActive',
    'ngFileUpload',
    'fileModel',
    'ngTagsInput',
    'ui.select',
    'ngImgCrop'
  ]
)
