source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


gem 'rails', '~> 5.0.3'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.0'
gem 'smarter_csv'
gem 'paperclip', '~> 5.1.0'
gem 'pg_search'
gem 'bcrypt', '~> 3.1.7'
gem 'mandrill-api'
gem 'friendly_id'
gem 'firebase'
gem 'active_model_serializers'

gem 'camaleon_cms', github: 'open-sourcepad/camaleon-cms', branch: 'fix-non-https-paths'
gem 'draper', github: 'drapergem/draper'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0' # Use Uglifier as compressor for JavaScript assets
gem 'coffee-rails', '~> 4.2' # Use CoffeeScript for .coffee assets and views
gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'therubyracer' # for uglifier's execjs dependency

gem 'httparty'
gem 'abn_search'
gem 'stripe'
gem 'whenever', require: false
gem 'acts-as-taggable-on'

# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors', require: 'rack/cors'

group :development, :test do
  gem 'rspec-rails', '~> 3.5'
  gem 'pry'
end

group :development do
  gem 'capistrano', '~> 3.6'
  gem 'capistrano-rvm'
  gem 'capistrano-rails'
  gem 'capistrano-bundler'
  gem 'capistrano3-puma'
  gem 'capistrano-rails-console', require: false
  gem 'capistrano-rake', require: false
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  #gem 'spring'
  #gem 'spring-watcher-listen', '~> 2.0.0'
end

group :development, :production do
  gem 'aws-sdk'
end

group :test do
  gem 'simplecov'
  gem 'codeclimate-test-reporter', '~> 1.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]


#################### Camaleon CMS include all gems for plugins and themes ####################
require './lib/plugin_routes'
instance_eval(PluginRoutes.draw_gems)
