require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/gulp'
# require 'capistrano/bundler'
require 'capistrano/npm'
require 'capistrano/nvm'
require 'capistrano/bower'

require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git

Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }
