source 'https://rubygems.org'

group :development do
  gem 'capistrano'#, '~> 3.1.0'
  gem 'capistrano-gulp', "~> 0.0.2"
  gem 'capistrano-npm'
  gem 'capistrano-nvm'
  gem 'capistrano-bower'
end

group :test do
  gem 'codeclimate-test-reporter', require: nil
  gem 'simplecov', require:  false
end
