development: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  database: <%= ENV['DB_NAME'] || 'dev_weplanrapi' %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  database: test_weplanrapi

production:
  <<: *default
